//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertSuiteTool.Reporting {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://reporting.elementexpress.com", ConfigurationName="Reporting.ExpressSoap")]
    public interface ExpressSoap {
        
        // CODEGEN: Parameter 'extendedParameters' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://reporting.elementexpress.com/TransactionQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExpressResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        CertSuiteTool.Reporting.TransactionQueryResponse TransactionQuery(CertSuiteTool.Reporting.TransactionQueryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://reporting.elementexpress.com")]
    public partial class Credentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountIDField;
        
        private string accountTokenField;
        
        private string acceptorIDField;
        
        private string newAccountTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
                this.RaisePropertyChanged("AccountID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccountToken {
            get {
                return this.accountTokenField;
            }
            set {
                this.accountTokenField = value;
                this.RaisePropertyChanged("AccountToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AcceptorID {
            get {
                return this.acceptorIDField;
            }
            set {
                this.acceptorIDField = value;
                this.RaisePropertyChanged("AcceptorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NewAccountToken {
            get {
                return this.newAccountTokenField;
            }
            set {
                this.newAccountTokenField = value;
                this.RaisePropertyChanged("NewAccountToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Response))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://reporting.elementexpress.com")]
    public abstract partial class ExpressResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string expressResponseCodeField;
        
        private string expressResponseMessageField;
        
        private string expressTransactionDateField;
        
        private string expressTransactionTimeField;
        
        private string expressTransactionTimezoneField;
        
        private ExtendedParameters[] extendedParametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ExpressResponseCode {
            get {
                return this.expressResponseCodeField;
            }
            set {
                this.expressResponseCodeField = value;
                this.RaisePropertyChanged("ExpressResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExpressResponseMessage {
            get {
                return this.expressResponseMessageField;
            }
            set {
                this.expressResponseMessageField = value;
                this.RaisePropertyChanged("ExpressResponseMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExpressTransactionDate {
            get {
                return this.expressTransactionDateField;
            }
            set {
                this.expressTransactionDateField = value;
                this.RaisePropertyChanged("ExpressTransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ExpressTransactionTime {
            get {
                return this.expressTransactionTimeField;
            }
            set {
                this.expressTransactionTimeField = value;
                this.RaisePropertyChanged("ExpressTransactionTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ExpressTransactionTimezone {
            get {
                return this.expressTransactionTimezoneField;
            }
            set {
                this.expressTransactionTimezoneField = value;
                this.RaisePropertyChanged("ExpressTransactionTimezone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ExtendedParameters[] ExtendedParameters {
            get {
                return this.extendedParametersField;
            }
            set {
                this.extendedParametersField = value;
                this.RaisePropertyChanged("ExtendedParameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://reporting.elementexpress.com")]
    public partial class ExtendedParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://reporting.elementexpress.com")]
    public partial class Response : ExpressResponse {
        
        private string reportingDataField;
        
        private string reportingIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReportingData {
            get {
                return this.reportingDataField;
            }
            set {
                this.reportingDataField = value;
                this.RaisePropertyChanged("ReportingData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReportingID {
            get {
                return this.reportingIDField;
            }
            set {
                this.reportingIDField = value;
                this.RaisePropertyChanged("ReportingID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://reporting.elementexpress.com")]
    public partial class Parameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIDField;
        
        private string terminalIDField;
        
        private string applicationIDField;
        
        private string approvalNumberField;
        
        private string approvedAmountField;
        
        private string expressTransactionDateField;
        
        private string expressTransactionTimeField;
        
        private string hostBatchIDField;
        
        private string hostItemIDField;
        
        private string hostReversalQueueIDField;
        
        private string originalAuthorizedAmountField;
        
        private string referenceNumberField;
        
        private string shiftIDField;
        
        private string sourceTransactionIDField;
        
        private TerminalType terminalTypeField;
        
        private string trackingIDField;
        
        private string transactionAmountField;
        
        private string transactionStatusField;
        
        private string transactionStatusCodeField;
        
        private string transactionTypeField;
        
        private string xIDField;
        
        private string sourceIPAddressField;
        
        private string externalInterfaceField;
        
        private LogTraceLevel logTraceLevelField;
        
        private string logTraceLevelNameField;
        
        private string machineNameField;
        
        private string sourceObjectField;
        
        private string processIDField;
        
        private string threadIDField;
        
        private BooleanType reverseOrderField;
        
        private string transactionDateTimeBeginField;
        
        private string transactionDateTimeEndField;
        
        private string transactionSetupIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TerminalID {
            get {
                return this.terminalIDField;
            }
            set {
                this.terminalIDField = value;
                this.RaisePropertyChanged("TerminalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ApplicationID {
            get {
                return this.applicationIDField;
            }
            set {
                this.applicationIDField = value;
                this.RaisePropertyChanged("ApplicationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ApprovalNumber {
            get {
                return this.approvalNumberField;
            }
            set {
                this.approvalNumberField = value;
                this.RaisePropertyChanged("ApprovalNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ApprovedAmount {
            get {
                return this.approvedAmountField;
            }
            set {
                this.approvedAmountField = value;
                this.RaisePropertyChanged("ApprovedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ExpressTransactionDate {
            get {
                return this.expressTransactionDateField;
            }
            set {
                this.expressTransactionDateField = value;
                this.RaisePropertyChanged("ExpressTransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ExpressTransactionTime {
            get {
                return this.expressTransactionTimeField;
            }
            set {
                this.expressTransactionTimeField = value;
                this.RaisePropertyChanged("ExpressTransactionTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string HostBatchID {
            get {
                return this.hostBatchIDField;
            }
            set {
                this.hostBatchIDField = value;
                this.RaisePropertyChanged("HostBatchID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string HostItemID {
            get {
                return this.hostItemIDField;
            }
            set {
                this.hostItemIDField = value;
                this.RaisePropertyChanged("HostItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string HostReversalQueueID {
            get {
                return this.hostReversalQueueIDField;
            }
            set {
                this.hostReversalQueueIDField = value;
                this.RaisePropertyChanged("HostReversalQueueID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string OriginalAuthorizedAmount {
            get {
                return this.originalAuthorizedAmountField;
            }
            set {
                this.originalAuthorizedAmountField = value;
                this.RaisePropertyChanged("OriginalAuthorizedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("ReferenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ShiftID {
            get {
                return this.shiftIDField;
            }
            set {
                this.shiftIDField = value;
                this.RaisePropertyChanged("ShiftID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SourceTransactionID {
            get {
                return this.sourceTransactionIDField;
            }
            set {
                this.sourceTransactionIDField = value;
                this.RaisePropertyChanged("SourceTransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public TerminalType TerminalType {
            get {
                return this.terminalTypeField;
            }
            set {
                this.terminalTypeField = value;
                this.RaisePropertyChanged("TerminalType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string TrackingID {
            get {
                return this.trackingIDField;
            }
            set {
                this.trackingIDField = value;
                this.RaisePropertyChanged("TrackingID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string TransactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                this.transactionAmountField = value;
                this.RaisePropertyChanged("TransactionAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string TransactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
                this.RaisePropertyChanged("TransactionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string TransactionStatusCode {
            get {
                return this.transactionStatusCodeField;
            }
            set {
                this.transactionStatusCodeField = value;
                this.RaisePropertyChanged("TransactionStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("TransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string XID {
            get {
                return this.xIDField;
            }
            set {
                this.xIDField = value;
                this.RaisePropertyChanged("XID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string SourceIPAddress {
            get {
                return this.sourceIPAddressField;
            }
            set {
                this.sourceIPAddressField = value;
                this.RaisePropertyChanged("SourceIPAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ExternalInterface {
            get {
                return this.externalInterfaceField;
            }
            set {
                this.externalInterfaceField = value;
                this.RaisePropertyChanged("ExternalInterface");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public LogTraceLevel LogTraceLevel {
            get {
                return this.logTraceLevelField;
            }
            set {
                this.logTraceLevelField = value;
                this.RaisePropertyChanged("LogTraceLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string LogTraceLevelName {
            get {
                return this.logTraceLevelNameField;
            }
            set {
                this.logTraceLevelNameField = value;
                this.RaisePropertyChanged("LogTraceLevelName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string MachineName {
            get {
                return this.machineNameField;
            }
            set {
                this.machineNameField = value;
                this.RaisePropertyChanged("MachineName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string SourceObject {
            get {
                return this.sourceObjectField;
            }
            set {
                this.sourceObjectField = value;
                this.RaisePropertyChanged("SourceObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string ProcessID {
            get {
                return this.processIDField;
            }
            set {
                this.processIDField = value;
                this.RaisePropertyChanged("ProcessID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string ThreadID {
            get {
                return this.threadIDField;
            }
            set {
                this.threadIDField = value;
                this.RaisePropertyChanged("ThreadID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public BooleanType ReverseOrder {
            get {
                return this.reverseOrderField;
            }
            set {
                this.reverseOrderField = value;
                this.RaisePropertyChanged("ReverseOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string TransactionDateTimeBegin {
            get {
                return this.transactionDateTimeBeginField;
            }
            set {
                this.transactionDateTimeBeginField = value;
                this.RaisePropertyChanged("TransactionDateTimeBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string TransactionDateTimeEnd {
            get {
                return this.transactionDateTimeEndField;
            }
            set {
                this.transactionDateTimeEndField = value;
                this.RaisePropertyChanged("TransactionDateTimeEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string TransactionSetupID {
            get {
                return this.transactionSetupIDField;
            }
            set {
                this.transactionSetupIDField = value;
                this.RaisePropertyChanged("TransactionSetupID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://reporting.elementexpress.com")]
    public enum TerminalType {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        PointOfSale,
        
        /// <remarks/>
        ECommerce,
        
        /// <remarks/>
        MOTO,
        
        /// <remarks/>
        FuelPump,
        
        /// <remarks/>
        ATM,
        
        /// <remarks/>
        Voice,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://reporting.elementexpress.com")]
    public enum LogTraceLevel {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Fatal = 2,
        
        /// <remarks/>
        Error = 4,
        
        /// <remarks/>
        Warning = 8,
        
        /// <remarks/>
        Information = 16,
        
        /// <remarks/>
        Trace = 32,
        
        /// <remarks/>
        Debug = 64,
        
        /// <remarks/>
        All = 128,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://reporting.elementexpress.com")]
    public enum BooleanType {
        
        /// <remarks/>
        False,
        
        /// <remarks/>
        True,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://reporting.elementexpress.com")]
    public partial class Application : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationIDField;
        
        private string applicationNameField;
        
        private string applicationVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ApplicationID {
            get {
                return this.applicationIDField;
            }
            set {
                this.applicationIDField = value;
                this.RaisePropertyChanged("ApplicationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
                this.RaisePropertyChanged("ApplicationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ApplicationVersion {
            get {
                return this.applicationVersionField;
            }
            set {
                this.applicationVersionField = value;
                this.RaisePropertyChanged("ApplicationVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionQuery", WrapperNamespace="https://reporting.elementexpress.com", IsWrapped=true)]
    public partial class TransactionQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://reporting.elementexpress.com", Order=0)]
        public CertSuiteTool.Reporting.Credentials credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://reporting.elementexpress.com", Order=1)]
        public CertSuiteTool.Reporting.Application application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://reporting.elementexpress.com", Order=2)]
        public CertSuiteTool.Reporting.Parameters parameters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://reporting.elementexpress.com", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CertSuiteTool.Reporting.ExtendedParameters[] extendedParameters;
        
        public TransactionQueryRequest() {
        }
        
        public TransactionQueryRequest(CertSuiteTool.Reporting.Credentials credentials, CertSuiteTool.Reporting.Application application, CertSuiteTool.Reporting.Parameters parameters, CertSuiteTool.Reporting.ExtendedParameters[] extendedParameters) {
            this.credentials = credentials;
            this.application = application;
            this.parameters = parameters;
            this.extendedParameters = extendedParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionQueryResponse", WrapperNamespace="https://reporting.elementexpress.com", IsWrapped=true)]
    public partial class TransactionQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://reporting.elementexpress.com", Order=0)]
        public CertSuiteTool.Reporting.Response response;
        
        public TransactionQueryResponse() {
        }
        
        public TransactionQueryResponse(CertSuiteTool.Reporting.Response response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExpressSoapChannel : CertSuiteTool.Reporting.ExpressSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExpressSoapClient : System.ServiceModel.ClientBase<CertSuiteTool.Reporting.ExpressSoap>, CertSuiteTool.Reporting.ExpressSoap {
        
        public ExpressSoapClient() {
        }
        
        public ExpressSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpressSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpressSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpressSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CertSuiteTool.Reporting.TransactionQueryResponse CertSuiteTool.Reporting.ExpressSoap.TransactionQuery(CertSuiteTool.Reporting.TransactionQueryRequest request) {
            return base.Channel.TransactionQuery(request);
        }
        
        public CertSuiteTool.Reporting.Response TransactionQuery(CertSuiteTool.Reporting.Credentials credentials, CertSuiteTool.Reporting.Application application, CertSuiteTool.Reporting.Parameters parameters, CertSuiteTool.Reporting.ExtendedParameters[] extendedParameters) {
            CertSuiteTool.Reporting.TransactionQueryRequest inValue = new CertSuiteTool.Reporting.TransactionQueryRequest();
            inValue.credentials = credentials;
            inValue.application = application;
            inValue.parameters = parameters;
            inValue.extendedParameters = extendedParameters;
            CertSuiteTool.Reporting.TransactionQueryResponse retVal = ((CertSuiteTool.Reporting.ExpressSoap)(this)).TransactionQuery(inValue);
            return retVal.response;
        }
    }
}
